### PR TITLE
Remove deprecated user credentials endpoints

### PR DESCRIPTION
**Pull request by ricardosantacattarina**

### CODE REVIEW

**Comment by ricardosantacattarina** [comment]
[[Docs] Remove deprecated credentials endpoints](https://trello.com/c/9V5RjYeM/253-docs-remove-deprecated-credentials-endpoints)

**Comment by fabyan-alexander** [comment]
[[Docs] Remove deprecated credentials endpoints](https://trello.com/c/9V5RjYeM/253-docs-remove-deprecated-credentials-endpoints)

**Review by fabyan-alexander — APPROVED** [review]
Nice work!
I saw that you also fixed our right column, so now I can see our endpoints much better!
Congratulations!
Btw, we are missing the credentials **agLeaderCredentials**, but let's fix that in another PR :rocket:

**Review by palomacione — APPROVED** [review]

**Comment by ricardosantacattarina** [comment]
> Nice work! I saw that you also fixed our right column, so now I can see our endpoints much better! Congratulations! Btw, we are missing the credentials **agLeaderCredentials**, but let's fix that in another PR rocket

I don't get it. Which agLeaderCredentials are missing? We do have documentation for AgLeader .

**Review by Vinniekun — APPROVED** [review]

**Pull request merged**
